name: docs

on:
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: docs.kibot.yaml
        dir: docs
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  fabrications_single:
    name: Fabrication - Single board
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: gerbers.kibot.yaml
        dir: Icicle_single
        board: Icicle.kicad_pcb
        schema: Icicle.sch

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: jlcpcb/bom.kibot.yaml
        dir: Icicle_single
        board: Icicle.kicad_pcb
        schema: Icicle.sch

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: jlcpcb/position.kibot.yaml
        dir: Icicle_single
        board: Icicle.kicad_pcb
        schema: Icicle.sch

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: Icicle_single
        path: Icicle_single


  fabrications_panel:
    name: Fabrication - Panel board
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make the Panel
      run: |
        docker run --rm -v $PWD:/pcb -w /pcb yaqwsx/kikit kikit panelize grid --space 3 --gridsize 5 1 --tabwidth 3 --tabheight 3 --htabs 1 --vtabs 2 --mousebites 0.5 0.8 -0.25 --radius 1 Icicle.kicad_pcb Icicle_panel.kicad_pcb

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: gerbers.kibot.yaml
        dir: Icicle_panel
        board: Icicle_panel.kicad_pcb
        schema: Icicle.sch

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: jlcpcb/bom.kibot.yaml
        dir: Icicle_panel
        board: Icicle_panel.kicad_pcb
        schema: Icicle.sch

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: jlcpcb/position.kibot.yaml
        dir: Icicle_panel
        board: Icicle_panel.kicad_pcb
        schema: Icicle.sch

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: Icicle_panel
        path: Icicle_panel
