name: docs

on:
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

env:
  KIKIT: docker run --rm -v $PWD:/pcb -w /pcb --user $UID:$GROUPS yaqwsx/kikit kikit

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: docs.kibot.yaml
        dir: docs
        board: Icicle.kicad_pcb
        schema: Icicle.sch

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  fabrications_single:
    name: Fabrication - Single board
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Export JLCPCB fabrication files
      run: |
        ${{ env.KIKIT }} fab jlcpcb --assembly --schematic Icicle.sch --ignore H1,P1,P2 Icicle.kicad_pcb Icicle_single
        mv Icicle_single/gerbers.zip Icicle_single/Icicle_single_${{ github.run_number }}.zip

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: Icicle_single
        path: |
          Icicle_single/*.zip
          Icicle_single/*.csv

  fabrications_panel:
    name: Fabrication - Panel board
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make the Panel
      run: |
        ${{ env.KIKIT }} panelize grid --space 3 --gridsize 5 1 --tabwidth 5 --tabheight 3 --htabs 1 --vtabs 4 --mousebites 0.5 0.8 -0.25 --radius 1 --railsTb 5 --tooling 2.5 2.5 1.152 --fiducials 10 2.5 1 2 Icicle.kicad_pcb Icicle_panel.kicad_pcb

    - name: Export JLCPCB fabrication files
      run: |
        ${{ env.KIKIT }} fab jlcpcb --assembly --schematic Icicle.sch --ignore H1,P1,P2 Icicle_panel.kicad_pcb Icicle_panel
        mv Icicle_panel/gerbers.zip Icicle_panel/Icicle_panel_${{ github.run_number }}.zip

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: Icicle_panel
        path: |
          Icicle_panel.kicad_pcb
          Icicle_panel/*.zip
          Icicle_panel/*.csv
