name: docs

on:
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  fabrications:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install KiCad
      uses: yaqwsx/KiKit

    - name: Install KiKit
      run: |
        sudo apt-get install --yes --no-install-recommends \
          zip inkscape make git libmagickwand-dev \
          libgraphicsmagick1-dev libmagickcore-dev \
          openscad bats
        python -m pip install --upgrade pip
        pip install --upgrade PcbDraw
        pip install --upgrade kikit

    - name: Make the Panel
      run: |
        kikit panelize grid --space 3 --gridsize 5 1 --tabwidth 3 --tabheight 3 --htabs 1 --vtabs 2 --mousebites 0.5 0.8 -0.25 --radius 1 Icicle.kicad_pcb Icicle_panel.kicad_pcb

    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: gerbers.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'

    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: jlcpcb/bom.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'

    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: jlcpcb/position.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        path: gerbers
